"""Added Recording model

Revision ID: 408f7b0e2fa2
Revises: b18dc521ee77
Create Date: 2026-07-03 22:58:04.353482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408f7b0e2fa2'
down_revision = 'b18dc521ee77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recording',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recording')
    # ### end Alembic commands ###
