"""added db

Revision ID: d3a537cf147c
Revises: f5b08f42dbec
Create Date: 2026-07-04 12:55:05.377101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a537cf147c'
down_revision = 'f5b08f42dbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcript_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.drop_column('transcript_status')

    # ### end Alembic commands ###
