"""Added Recording model

Revision ID: f5b08f42dbec
Revises: 408f7b0e2fa2
Create Date: 2026-07-03 23:28:09.836901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b08f42dbec'
down_revision = '408f7b0e2fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('media_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('transcript', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('filename')
        batch_op.drop_column('original_name')
        batch_op.drop_column('uploaded_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('original_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('transcript')
        batch_op.drop_column('file_path')
        batch_op.drop_column('media_type')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
